### ISSUE TITLE
Mapping port issue 

### ISSUE THREAD

**Issue by chengxinjing** [fabianoo/spring-localstack#12]
at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7
.RELEASE]
... 26 common frames omitted
Caused by: java.lang.IllegalArgumentException: Port: 4585 does not exist
at xyz.fabiano.spring.localstack.legacy.Container.lambda$getExternalPortFor$1(Container.java:90) ~[spring-localstack-0.0.10.jar!/:na]
at java.util.Optional.orElseThrow(Optional.java:290) ~[na:1.8.0_201]
at xyz.fabiano.spring.localstack.legacy.Container.getExternalPortFor(Container.java:90) ~[spring-localstack-0.0.10.jar!/:na]
at xyz.fabiano.spring.localstack.legacy.LocalstackDocker.endpointForPort(LocalstackDocker.java:208) ~[spring-localstack-0.0.10.jar!/:na]
at xyz.fabiano.spring.localstack.legacy.LocalstackDocker.endpointForService(LocalstackDocker.java:202) ~[spring-localstack-0.0.10.jar!/:na]
at xyz.fabiano.spring.localstack.legacy.LocalstackDocker.getEndpointStepFunction(LocalstackDocker.java:189) ~[spring-localstack-0.0.10.jar!/:na]
at xyz.fabiano.spring.localstack.support.AbstractAmazonDockerClientsHolder.decorateWithConfigsAndBuild(AbstractAmazonDockerClientsHolder.java:35) ~[spring-localstack
-0.0.10.jar!/:na]
at xyz.fabiano.spring.localstack.support.AmazonDockerClientsHolder.awsStepFunctions(AmazonDockerClientsHolder.java:157) ~[spring-localstack-0.0.10.jar!/:na]
at xyz.fabiano.spring.localstack.autoconfigure.EveryAwsClientAutoConfiguration.awsStepFunctions(EveryAwsClientAutoConfiguration.java:111) ~[spring-localstack-0.0.10.
jar!/:na]
at xyz.fabiano.spring.localstack.autoconfigure.EveryAwsClientAutoConfiguration$$EnhancerBySpringCGLIB$$8e0061d3.CGLIB$awsStepFunctions$7(<generated>) ~[spring-locals
tack-0.0.10.jar!/:na]
at xyz.fabiano.spring.localstack.autoconfigure.EveryAwsClientAutoConfiguration$$EnhancerBySpringCGLIB$$8e0061d3$$FastClassBySpringCGLIB$$cbc9ad80.invoke(<generated>)
 ~[spring-localstack-0.0.10.jar!/:na]
at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-4.3.7.RELE
ASE.jar!/:4.3.7.RELEASE]
at xyz.fabiano.spring.localstack.autoconfigure.EveryAwsClientAutoConfiguration$$EnhancerBySpringCGLIB$$8e0061d3.awsStepFunctions(<generated>) ~[spring-localstack-0.0
.10.jar!/:na]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]

**Comment by chengxinjing** [comment]
should modify the Port mapping  to 4567-4596 in  Container.java

**Comment by soelvar** [comment]
Maybe  create a pull request - describe which service you are using that is running on the port number... And possibly a link to aws documentation.
